language: php

sudo: false

php:
    - 7.1
    - hhvm

env:
    global:
     - COMPOSER_GLOBAL_FLAGS=--no-interaction --prefer-source -o

matrix:
    allow_failures:
        - php: hhvm

install:
    # Update Composer
    - travis_retry composer self-update

    # Install Nette Tester
    - travis_retry composer update ${COMPOSER_GLOBAL_FLAGS}

script:
    # Run PHP linter
    - bin/linter

    # Run CodeSniffer
    - bin/codesniffer

    # Show Nette Tester environment
    - bin/tester-info

    # Run Nette Tester
    - bin/tester

after_failure:
    # Print *.actual content
    - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

cache:
    directories:
        - $HOME/.composer/cache
