language: php

sudo: false

php:
    - 7.3
    - 7.4

env:
    global:
     - COMPOSER_GLOBAL_FLAGS=--no-interaction --prefer-source -o

matrix:
    allow_failures:
        - php: hhvm

install:
    - travis_retry composer update ${COMPOSER_GLOBAL_FLAGS}

script:
    # Run QA
    - composer qa

    # Run Nette Tester
    - composer tester

    # Run Phpstan
    - composer phpstan

after_failure:
    # Print *.actual content
    - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

cache:
    directories:
        - $HOME/.composer/cache
